- hosts: terraform-ansible
  tasks:
    - name: installing python and virtualenv
      become: true
      apt:
        update_cache: yes
        pkg:
          - python3
          - virtualenv

    - name: Git Clone
      ansible.builtin.git:
        repo: https://github.com/alura-cursos/clientes-leo-api.git
        dest: /home/ubuntu/tcc
        version: master

    - name: installing dependencies with pip
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework

    - name: changing allowed host on setting file
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: "ALLOWED_HOSTS = ['*']"
        backrefs: yes
