apiVersion: v1
kind: Pod
metadata:
  name: database-noticias
  labels:
    app: database-noticias
spec:
  containers:
    - name: database-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: database-configmap
      resources:
        limits:
          memory: 512Mi
          cpu: "2"

      # env:
      #   - name: "MYSQL_ROOT_PASSWORD"
      #     valueFrom:
      #       configMapKeyRef:
      #       name: database-configmap
      #       key: MYSQL_ROOT_PASSWORD
