- hosts: terraform-ansible
  tasks:
    - name: installing python and virtualenv
      become: true
      apt:
        update_cache: yes
        pkg: 
          - python3
          - virtualenv
    - name: installing dependencies with pip
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework