name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ["1.18", "1.17", ">=1.19"]
        os: ["ubuntu-latest", "windows-latest", "ubuntu-latest"]
    defaults:
      run:
        working-directory: ci-cd
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build Database
        run: docker-compose build

      - name: Create Database
        run: docker-compose up -d

      - name: Test
        run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ci-cd
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.5

      - name: Build
        run: go build -v main.go
