name: CI/CD Workflow

# on:
#   workflow_dispatch:

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ci-cd

jobs:
  test:
    name: Test on go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ["1.18"]
        os: ["ubuntu-latest"]
        # go_version: ["1.18", ">=1.19"]
        # os: ["ubuntu-latest", "ubuntu-20.04"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build Database
        run: docker-compose build

      - name: Create Database
        run: docker-compose up -d

      - name: Test
        run: go test -v main_test.go

      - name: Build
        run: go build -v main.go

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ./main

  # build:
  #   name: Build on Go
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Build
  #       run: go build -v main.go

  #     - name: Upload a Build Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: api
  #         path: ./main

  docker:
    needs: test
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
